### ISSUE TITLE
FR: Ability to add layout handles to page types

### ISSUE THREAD

**Issue by adamj88** [rskuipers/RK_TypeCMS#11]
Currently you are able to define a single template to render the content and fields added by TypeCMS.

There may be some instances in which you require more control over the layout of a specific page type. E.g. you may want to force the template to `2column-left` view and add a submenu in the left column for all pages with that type.

To do this the page would require a layout handle adding then using Magento's layout XML in a theme you can manipulate the page layout as a whole. 

The only alternative is to create page layouts in an additional module `config.xml` like so: 

```xml
    <global>
        <page>
            <layouts>
                <custom_layout translate="label">
                    <label>Custom Layout Label</label>
                    <template>page/1column.phtml</template>
                    <layout_handle>custom_layout_handle</layout_handle>
                </custom_layout>
            </layouts>            
        </page>
    </global>
```

**Comment by rskuipers** [comment]
Great idea @adamj88! I will review your PR soon, it's been a bit chaotic for me this week.

**Comment by rskuipers** [comment]
@adamj88 I have pushed a new tag: 3.1.0
