### ISSUE TITLE
Move TypeCMS Fields to Content Tab

### ISSUE THREAD

**Issue by Skinwalker** [rskuipers/RK_TypeCMS#5]
Is there a way to move the custom Fields to the Content Tab instead of the Information Tab?

**Comment by rskuipers** [comment]
@Skinwalker By default, no.
This would require some changes to the module, it's been a while since I've worked with it (Magento in general) so I don't know what the impact is.

**Comment by Skinwalker** [comment]
I tried to make some chances in the config.xml but that didn't work.

It was just a question - because is more logic that the "Content-Input" is in the Content-Tab.
But its ok - nice extension btw: saved me many hours of HTML-Editor work ;)

**Comment by rskuipers** [comment]
@Skinwalker It would've made more sense, yes.

Thanks! I'm glad I made your life a little easier :)
