### ISSUE TITLE
Update Compatibility with CleverCMS (Now Bubble CMS Tree)

### ISSUE THREAD

**Issue by adamj88** [rskuipers/RK_TypeCMS#9]
Clever CMS has had yet another name space change and is under Bubble CMS Tree.

This causes a couple of issues:

- SQL relations fail to set up correctly
- Helper function `hasCleverCMS()` always returns false

**Comment by adamj88** [comment]
Recommend bumping the version number to 2.3.0 as it will cause significant compatibility issues.

**Comment by rskuipers** [comment]
@adamj88 Wow, I didn't expect them to have another namespace change... very annoying.
Great job on the PR :+1:! I will check it this evening.

Also, I think this would force us to up the major since it's a BC break. So 3.0.0 incoming I guess :)

**Comment by adamj88** [comment]
No worries :) I agree 3.0.0 would be better.

Seems they've moved the module over to: https://www.bubbleshop.net/magento-cms-tree.html - should hopefully be the last time it changes.

Everything else seems to be compatible with the CMS Tree module too, pretty good considering the codebase hasn't changed in ~2 years.

**Comment by rskuipers** [comment]
@adamj88 Looks like my plan to do as little coupling as possible worked out nicely :)
I do hope that's the last time!

Just pushed version 3.0.0, let me know if it works :)
